// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: bible.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book    string `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Chapter int32  `protobuf:"varint,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Verse   int32  `protobuf:"varint,3,opt,name=verse,proto3" json:"verse,omitempty"`
	Text    string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Verse) Reset() {
	*x = Verse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bible_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Verse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verse) ProtoMessage() {}

func (x *Verse) ProtoReflect() protoreflect.Message {
	mi := &file_bible_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verse.ProtoReflect.Descriptor instead.
func (*Verse) Descriptor() ([]byte, []int) {
	return file_bible_proto_rawDescGZIP(), []int{0}
}

func (x *Verse) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

func (x *Verse) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *Verse) GetVerse() int32 {
	if x != nil {
		return x.Verse
	}
	return 0
}

func (x *Verse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type VerseRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book       string   `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Chapter    int32    `protobuf:"varint,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
	StartVerse int32    `protobuf:"varint,3,opt,name=start_verse,json=startVerse,proto3" json:"start_verse,omitempty"`
	EndVerse   int32    `protobuf:"varint,4,opt,name=end_verse,json=endVerse,proto3" json:"end_verse,omitempty"`
	Verses     []string `protobuf:"bytes,5,rep,name=verses,proto3" json:"verses,omitempty"`
}

func (x *VerseRange) Reset() {
	*x = VerseRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bible_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerseRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerseRange) ProtoMessage() {}

func (x *VerseRange) ProtoReflect() protoreflect.Message {
	mi := &file_bible_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerseRange.ProtoReflect.Descriptor instead.
func (*VerseRange) Descriptor() ([]byte, []int) {
	return file_bible_proto_rawDescGZIP(), []int{1}
}

func (x *VerseRange) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

func (x *VerseRange) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *VerseRange) GetStartVerse() int32 {
	if x != nil {
		return x.StartVerse
	}
	return 0
}

func (x *VerseRange) GetEndVerse() int32 {
	if x != nil {
		return x.EndVerse
	}
	return 0
}

func (x *VerseRange) GetVerses() []string {
	if x != nil {
		return x.Verses
	}
	return nil
}

type BiblePlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day          int32  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	StartReading string `protobuf:"bytes,2,opt,name=startReading,proto3" json:"startReading,omitempty"`
	EndReading   string `protobuf:"bytes,3,opt,name=endReading,proto3" json:"endReading,omitempty"`
}

func (x *BiblePlan) Reset() {
	*x = BiblePlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bible_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiblePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiblePlan) ProtoMessage() {}

func (x *BiblePlan) ProtoReflect() protoreflect.Message {
	mi := &file_bible_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiblePlan.ProtoReflect.Descriptor instead.
func (*BiblePlan) Descriptor() ([]byte, []int) {
	return file_bible_proto_rawDescGZIP(), []int{2}
}

func (x *BiblePlan) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *BiblePlan) GetStartReading() string {
	if x != nil {
		return x.StartReading
	}
	return ""
}

func (x *BiblePlan) GetEndReading() string {
	if x != nil {
		return x.EndReading
	}
	return ""
}

var File_bible_proto protoreflect.FileDescriptor

var file_bible_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x5f, 0x0a, 0x05, 0x56, 0x65, 0x72, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x22, 0x90, 0x01, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x73, 0x65, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x56, 0x65, 0x72, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x56, 0x65, 0x72, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x65, 0x72, 0x73, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76,
	0x65, 0x72, 0x73, 0x65, 0x73, 0x22, 0x61, 0x0a, 0x09, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x6c,
	0x61, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x64, 0x61, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x61,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x76, 0x65, 0x2d, 0x6d, 0x69, 0x72,
	0x2f, 0x64, 0x69, 0x69, 0x76, 0x69, 0x78, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bible_proto_rawDescOnce sync.Once
	file_bible_proto_rawDescData = file_bible_proto_rawDesc
)

func file_bible_proto_rawDescGZIP() []byte {
	file_bible_proto_rawDescOnce.Do(func() {
		file_bible_proto_rawDescData = protoimpl.X.CompressGZIP(file_bible_proto_rawDescData)
	})
	return file_bible_proto_rawDescData
}

var file_bible_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bible_proto_goTypes = []interface{}{
	(*Verse)(nil),      // 0: pb.Verse
	(*VerseRange)(nil), // 1: pb.VerseRange
	(*BiblePlan)(nil),  // 2: pb.BiblePlan
}
var file_bible_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bible_proto_init() }
func file_bible_proto_init() {
	if File_bible_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bible_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Verse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bible_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerseRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bible_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiblePlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bible_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bible_proto_goTypes,
		DependencyIndexes: file_bible_proto_depIdxs,
		MessageInfos:      file_bible_proto_msgTypes,
	}.Build()
	File_bible_proto = out.File
	file_bible_proto_rawDesc = nil
	file_bible_proto_goTypes = nil
	file_bible_proto_depIdxs = nil
}
