// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: rpc_bible.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchVerseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input     string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	BiblePath string `protobuf:"bytes,2,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`
}

func (x *SearchVerseRequest) Reset() {
	*x = SearchVerseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchVerseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVerseRequest) ProtoMessage() {}

func (x *SearchVerseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVerseRequest.ProtoReflect.Descriptor instead.
func (*SearchVerseRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{0}
}

func (x *SearchVerseRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *SearchVerseRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

type GetVerseRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input     string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	BiblePath string `protobuf:"bytes,2,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`
}

func (x *GetVerseRangeRequest) Reset() {
	*x = GetVerseRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVerseRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerseRangeRequest) ProtoMessage() {}

func (x *GetVerseRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerseRangeRequest.ProtoReflect.Descriptor instead.
func (*GetVerseRangeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{1}
}

func (x *GetVerseRangeRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *GetVerseRangeRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

type SearchByKeywordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BiblePath string `protobuf:"bytes,1,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`
	Keyword   string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *SearchByKeywordRequest) Reset() {
	*x = SearchByKeywordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchByKeywordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByKeywordRequest) ProtoMessage() {}

func (x *SearchByKeywordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByKeywordRequest.ProtoReflect.Descriptor instead.
func (*SearchByKeywordRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{2}
}

func (x *SearchByKeywordRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

func (x *SearchByKeywordRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListAllBooksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BiblePath string `protobuf:"bytes,1,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`
}

func (x *ListAllBooksRequest) Reset() {
	*x = ListAllBooksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllBooksRequest) ProtoMessage() {}

func (x *ListAllBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllBooksRequest.ProtoReflect.Descriptor instead.
func (*ListAllBooksRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{3}
}

func (x *ListAllBooksRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

type ListAllChaptersOfBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BiblePath string `protobuf:"bytes,1,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`
	BookName  string `protobuf:"bytes,2,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
}

func (x *ListAllChaptersOfBookRequest) Reset() {
	*x = ListAllChaptersOfBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllChaptersOfBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllChaptersOfBookRequest) ProtoMessage() {}

func (x *ListAllChaptersOfBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllChaptersOfBookRequest.ProtoReflect.Descriptor instead.
func (*ListAllChaptersOfBookRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{4}
}

func (x *ListAllChaptersOfBookRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

func (x *ListAllChaptersOfBookRequest) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

type ListAllVersesOfChapterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BiblePath     string `protobuf:"bytes,1,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`
	BookName      string `protobuf:"bytes,2,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	ChapterNumber int32  `protobuf:"varint,3,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
}

func (x *ListAllVersesOfChapterRequest) Reset() {
	*x = ListAllVersesOfChapterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllVersesOfChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllVersesOfChapterRequest) ProtoMessage() {}

func (x *ListAllVersesOfChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllVersesOfChapterRequest.ProtoReflect.Descriptor instead.
func (*ListAllVersesOfChapterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{5}
}

func (x *ListAllVersesOfChapterRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

func (x *ListAllVersesOfChapterRequest) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *ListAllVersesOfChapterRequest) GetChapterNumber() int32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

type RandomVerseGeneratorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BiblePath string `protobuf:"bytes,1,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`
}

func (x *RandomVerseGeneratorRequest) Reset() {
	*x = RandomVerseGeneratorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomVerseGeneratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomVerseGeneratorRequest) ProtoMessage() {}

func (x *RandomVerseGeneratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomVerseGeneratorRequest.ProtoReflect.Descriptor instead.
func (*RandomVerseGeneratorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{6}
}

func (x *RandomVerseGeneratorRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

type SearchByTopicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BiblePath string `protobuf:"bytes,1,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`
	Topic     string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *SearchByTopicRequest) Reset() {
	*x = SearchByTopicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchByTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByTopicRequest) ProtoMessage() {}

func (x *SearchByTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByTopicRequest.ProtoReflect.Descriptor instead.
func (*SearchByTopicRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{7}
}

func (x *SearchByTopicRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

func (x *SearchByTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type CompareTranslationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Translation1Path string `protobuf:"bytes,1,opt,name=translation1_path,json=translation1Path,proto3" json:"translation1_path,omitempty"`
	Translation2Path string `protobuf:"bytes,2,opt,name=translation2_path,json=translation2Path,proto3" json:"translation2_path,omitempty"`
	BookName         string `protobuf:"bytes,3,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	ChapterNumber    int32  `protobuf:"varint,4,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	VerseNumber      int32  `protobuf:"varint,5,opt,name=verse_number,json=verseNumber,proto3" json:"verse_number,omitempty"`
}

func (x *CompareTranslationsRequest) Reset() {
	*x = CompareTranslationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompareTranslationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareTranslationsRequest) ProtoMessage() {}

func (x *CompareTranslationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareTranslationsRequest.ProtoReflect.Descriptor instead.
func (*CompareTranslationsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{8}
}

func (x *CompareTranslationsRequest) GetTranslation1Path() string {
	if x != nil {
		return x.Translation1Path
	}
	return ""
}

func (x *CompareTranslationsRequest) GetTranslation2Path() string {
	if x != nil {
		return x.Translation2Path
	}
	return ""
}

func (x *CompareTranslationsRequest) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *CompareTranslationsRequest) GetChapterNumber() int32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *CompareTranslationsRequest) GetVerseNumber() int32 {
	if x != nil {
		return x.VerseNumber
	}
	return 0
}

type CrossReferenceLookupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BiblePath     string `protobuf:"bytes,1,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`
	BookName      string `protobuf:"bytes,2,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	ChapterNumber int32  `protobuf:"varint,3,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	VerseNumber   int32  `protobuf:"varint,4,opt,name=verse_number,json=verseNumber,proto3" json:"verse_number,omitempty"`
}

func (x *CrossReferenceLookupRequest) Reset() {
	*x = CrossReferenceLookupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossReferenceLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossReferenceLookupRequest) ProtoMessage() {}

func (x *CrossReferenceLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossReferenceLookupRequest.ProtoReflect.Descriptor instead.
func (*CrossReferenceLookupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{9}
}

func (x *CrossReferenceLookupRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

func (x *CrossReferenceLookupRequest) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *CrossReferenceLookupRequest) GetChapterNumber() int32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *CrossReferenceLookupRequest) GetVerseNumber() int32 {
	if x != nil {
		return x.VerseNumber
	}
	return 0
}

type VerseOfTheDayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BiblePath string `protobuf:"bytes,1,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`
}

func (x *VerseOfTheDayRequest) Reset() {
	*x = VerseOfTheDayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerseOfTheDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerseOfTheDayRequest) ProtoMessage() {}

func (x *VerseOfTheDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerseOfTheDayRequest.ProtoReflect.Descriptor instead.
func (*VerseOfTheDayRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{10}
}

func (x *VerseOfTheDayRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

type ListAllChaptersOfBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chapter int32 `protobuf:"varint,1,opt,name=chapter,proto3" json:"chapter,omitempty"`
}

func (x *ListAllChaptersOfBookResponse) Reset() {
	*x = ListAllChaptersOfBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllChaptersOfBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllChaptersOfBookResponse) ProtoMessage() {}

func (x *ListAllChaptersOfBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllChaptersOfBookResponse.ProtoReflect.Descriptor instead.
func (*ListAllChaptersOfBookResponse) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{11}
}

func (x *ListAllChaptersOfBookResponse) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

type ListAllChaptersOfBookUnaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chapter []int32 `protobuf:"varint,1,rep,packed,name=chapter,proto3" json:"chapter,omitempty"`
}

func (x *ListAllChaptersOfBookUnaryResponse) Reset() {
	*x = ListAllChaptersOfBookUnaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllChaptersOfBookUnaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllChaptersOfBookUnaryResponse) ProtoMessage() {}

func (x *ListAllChaptersOfBookUnaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllChaptersOfBookUnaryResponse.ProtoReflect.Descriptor instead.
func (*ListAllChaptersOfBookUnaryResponse) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{12}
}

func (x *ListAllChaptersOfBookUnaryResponse) GetChapter() []int32 {
	if x != nil {
		return x.Chapter
	}
	return nil
}

type ListAllBooksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookName string `protobuf:"bytes,1,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
}

func (x *ListAllBooksResponse) Reset() {
	*x = ListAllBooksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllBooksResponse) ProtoMessage() {}

func (x *ListAllBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllBooksResponse.ProtoReflect.Descriptor instead.
func (*ListAllBooksResponse) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{13}
}

func (x *ListAllBooksResponse) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

type GenerateReadingPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BiblePath      string `protobuf:"bytes,1,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`                   // Path to the XML file containing the Bible data
	DurationInDays int32  `protobuf:"varint,2,opt,name=duration_in_days,json=durationInDays,proto3" json:"duration_in_days,omitempty"` // Duration in days for reading the entire scripture
}

func (x *GenerateReadingPlanRequest) Reset() {
	*x = GenerateReadingPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateReadingPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReadingPlanRequest) ProtoMessage() {}

func (x *GenerateReadingPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReadingPlanRequest.ProtoReflect.Descriptor instead.
func (*GenerateReadingPlanRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{14}
}

func (x *GenerateReadingPlanRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

func (x *GenerateReadingPlanRequest) GetDurationInDays() int32 {
	if x != nil {
		return x.DurationInDays
	}
	return 0
}

type GetCurrentReadingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BiblePath      string                 `protobuf:"bytes,1,opt,name=bible_path,json=biblePath,proto3" json:"bible_path,omitempty"`                   // Path to the XML file containing the Bible data
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`                   // Start date of the reading plan
	CurrentDate    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=current_date,json=currentDate,proto3" json:"current_date,omitempty"`             // Current date for which to get the reading
	DurationInDays int32                  `protobuf:"varint,4,opt,name=duration_in_days,json=durationInDays,proto3" json:"duration_in_days,omitempty"` // Duration in days for reading the entire scripture
}

func (x *GetCurrentReadingRequest) Reset() {
	*x = GetCurrentReadingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentReadingRequest) ProtoMessage() {}

func (x *GetCurrentReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentReadingRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentReadingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{15}
}

func (x *GetCurrentReadingRequest) GetBiblePath() string {
	if x != nil {
		return x.BiblePath
	}
	return ""
}

func (x *GetCurrentReadingRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetCurrentReadingRequest) GetCurrentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentDate
	}
	return nil
}

func (x *GetCurrentReadingRequest) GetDurationInDays() int32 {
	if x != nil {
		return x.DurationInDays
	}
	return 0
}

type DownloadBibleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BibleTranslation string `protobuf:"bytes,1,opt,name=bible_translation,json=bibleTranslation,proto3" json:"bible_translation,omitempty"`
}

func (x *DownloadBibleRequest) Reset() {
	*x = DownloadBibleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadBibleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBibleRequest) ProtoMessage() {}

func (x *DownloadBibleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBibleRequest.ProtoReflect.Descriptor instead.
func (*DownloadBibleRequest) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{16}
}

func (x *DownloadBibleRequest) GetBibleTranslation() string {
	if x != nil {
		return x.BibleTranslation
	}
	return ""
}

type DownloadBibleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DownloadBibleResponse) Reset() {
	*x = DownloadBibleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_bible_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadBibleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBibleResponse) ProtoMessage() {}

func (x *DownloadBibleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_bible_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBibleResponse.ProtoReflect.Descriptor instead.
func (*DownloadBibleResponse) Descriptor() ([]byte, []int) {
	return file_rpc_bible_proto_rawDescGZIP(), []int{17}
}

func (x *DownloadBibleResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rpc_bible_proto protoreflect.FileDescriptor

var file_rpc_bible_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x70, 0x63, 0x5f, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x56, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x22, 0x4b, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x65, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x51,
	0x0a, 0x16, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69,
	0x62, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x34, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69,
	0x62, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x5a, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x6c, 0x6c, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x4f, 0x66, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c, 0x65,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x62,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x56,
	0x65, 0x72, 0x73, 0x65, 0x73, 0x4f, 0x66, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x62, 0x6c, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3c, 0x0a, 0x1b, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c, 0x65,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x62,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x4b, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x42, 0x79, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x22, 0xdd, 0x01, 0x0a, 0x1a, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x31, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x2b, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x21, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x76, 0x65, 0x72, 0x73, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0xa3, 0x01, 0x0a, 0x1b, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x76, 0x65,
	0x72, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x35, 0x0a, 0x14, 0x56, 0x65, 0x72,
	0x73, 0x65, 0x4f, 0x66, 0x54, 0x68, 0x65, 0x44, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x22, 0x39, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x73, 0x4f, 0x66, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x22, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x4f, 0x66,
	0x42, 0x6f, 0x6f, 0x6b, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x14, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x65, 0x0a, 0x1a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x28, 0x0a,
	0x10, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x79,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x22, 0xdd, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x3d,
	0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a,
	0x10, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x79,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x22, 0x43, 0x0a, 0x14, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x11, 0x62, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x62, 0x69, 0x62, 0x6c,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x15,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x69, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x76, 0x65, 0x2d, 0x6d, 0x69,
	0x72, 0x2f, 0x64, 0x69, 0x69, 0x76, 0x69, 0x78, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_bible_proto_rawDescOnce sync.Once
	file_rpc_bible_proto_rawDescData = file_rpc_bible_proto_rawDesc
)

func file_rpc_bible_proto_rawDescGZIP() []byte {
	file_rpc_bible_proto_rawDescOnce.Do(func() {
		file_rpc_bible_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_bible_proto_rawDescData)
	})
	return file_rpc_bible_proto_rawDescData
}

var file_rpc_bible_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_rpc_bible_proto_goTypes = []interface{}{
	(*SearchVerseRequest)(nil),                 // 0: pb.SearchVerseRequest
	(*GetVerseRangeRequest)(nil),               // 1: pb.GetVerseRangeRequest
	(*SearchByKeywordRequest)(nil),             // 2: pb.SearchByKeywordRequest
	(*ListAllBooksRequest)(nil),                // 3: pb.ListAllBooksRequest
	(*ListAllChaptersOfBookRequest)(nil),       // 4: pb.ListAllChaptersOfBookRequest
	(*ListAllVersesOfChapterRequest)(nil),      // 5: pb.ListAllVersesOfChapterRequest
	(*RandomVerseGeneratorRequest)(nil),        // 6: pb.RandomVerseGeneratorRequest
	(*SearchByTopicRequest)(nil),               // 7: pb.SearchByTopicRequest
	(*CompareTranslationsRequest)(nil),         // 8: pb.CompareTranslationsRequest
	(*CrossReferenceLookupRequest)(nil),        // 9: pb.CrossReferenceLookupRequest
	(*VerseOfTheDayRequest)(nil),               // 10: pb.VerseOfTheDayRequest
	(*ListAllChaptersOfBookResponse)(nil),      // 11: pb.ListAllChaptersOfBookResponse
	(*ListAllChaptersOfBookUnaryResponse)(nil), // 12: pb.ListAllChaptersOfBookUnaryResponse
	(*ListAllBooksResponse)(nil),               // 13: pb.ListAllBooksResponse
	(*GenerateReadingPlanRequest)(nil),         // 14: pb.GenerateReadingPlanRequest
	(*GetCurrentReadingRequest)(nil),           // 15: pb.GetCurrentReadingRequest
	(*DownloadBibleRequest)(nil),               // 16: pb.DownloadBibleRequest
	(*DownloadBibleResponse)(nil),              // 17: pb.DownloadBibleResponse
	(*timestamppb.Timestamp)(nil),              // 18: google.protobuf.Timestamp
}
var file_rpc_bible_proto_depIdxs = []int32{
	18, // 0: pb.GetCurrentReadingRequest.start_date:type_name -> google.protobuf.Timestamp
	18, // 1: pb.GetCurrentReadingRequest.current_date:type_name -> google.protobuf.Timestamp
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_bible_proto_init() }
func file_rpc_bible_proto_init() {
	if File_rpc_bible_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_bible_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchVerseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVerseRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchByKeywordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllBooksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllChaptersOfBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllVersesOfChapterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomVerseGeneratorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchByTopicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompareTranslationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossReferenceLookupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerseOfTheDayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllChaptersOfBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllChaptersOfBookUnaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllBooksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateReadingPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentReadingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadBibleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_bible_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadBibleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_bible_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_bible_proto_goTypes,
		DependencyIndexes: file_rpc_bible_proto_depIdxs,
		MessageInfos:      file_rpc_bible_proto_msgTypes,
	}.Build()
	File_rpc_bible_proto = out.File
	file_rpc_bible_proto_rawDesc = nil
	file_rpc_bible_proto_goTypes = nil
	file_rpc_bible_proto_depIdxs = nil
}
