// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: repost.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create a repost
type CreateRepostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalPostId string `protobuf:"bytes,2,opt,name=original_post_id,json=originalPostId,proto3" json:"original_post_id,omitempty"`
}

func (x *CreateRepostRequest) Reset() {
	*x = CreateRepostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repost_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRepostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepostRequest) ProtoMessage() {}

func (x *CreateRepostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repost_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepostRequest.ProtoReflect.Descriptor instead.
func (*CreateRepostRequest) Descriptor() ([]byte, []int) {
	return file_repost_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRepostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRepostRequest) GetOriginalPostId() string {
	if x != nil {
		return x.OriginalPostId
	}
	return ""
}

// Request to get a single repost by ID
type GetRepostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRepostRequest) Reset() {
	*x = GetRepostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repost_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRepostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepostRequest) ProtoMessage() {}

func (x *GetRepostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repost_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepostRequest.ProtoReflect.Descriptor instead.
func (*GetRepostRequest) Descriptor() ([]byte, []int) {
	return file_repost_proto_rawDescGZIP(), []int{1}
}

func (x *GetRepostRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Request to get reposts by a user ID
type GetRepostsByUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetRepostsByUserRequest) Reset() {
	*x = GetRepostsByUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repost_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRepostsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepostsByUserRequest) ProtoMessage() {}

func (x *GetRepostsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repost_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepostsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetRepostsByUserRequest) Descriptor() ([]byte, []int) {
	return file_repost_proto_rawDescGZIP(), []int{2}
}

func (x *GetRepostsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Request to delete a repost
type DeleteRepostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRepostRequest) Reset() {
	*x = DeleteRepostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repost_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRepostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepostRequest) ProtoMessage() {}

func (x *DeleteRepostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repost_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepostRequest.ProtoReflect.Descriptor instead.
func (*DeleteRepostRequest) Descriptor() ([]byte, []int) {
	return file_repost_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRepostRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response for a single repost
type RepostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repost *Repost `protobuf:"bytes,1,opt,name=repost,proto3" json:"repost,omitempty"`
}

func (x *RepostResponse) Reset() {
	*x = RepostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repost_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepostResponse) ProtoMessage() {}

func (x *RepostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repost_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepostResponse.ProtoReflect.Descriptor instead.
func (*RepostResponse) Descriptor() ([]byte, []int) {
	return file_repost_proto_rawDescGZIP(), []int{4}
}

func (x *RepostResponse) GetRepost() *Repost {
	if x != nil {
		return x.Repost
	}
	return nil
}

// Response for multiple reposts
type RepostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reposts []*Repost `protobuf:"bytes,1,rep,name=reposts,proto3" json:"reposts,omitempty"`
}

func (x *RepostsResponse) Reset() {
	*x = RepostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repost_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepostsResponse) ProtoMessage() {}

func (x *RepostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repost_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepostsResponse.ProtoReflect.Descriptor instead.
func (*RepostsResponse) Descriptor() ([]byte, []int) {
	return file_repost_proto_rawDescGZIP(), []int{5}
}

func (x *RepostsResponse) GetReposts() []*Repost {
	if x != nil {
		return x.Reposts
	}
	return nil
}

// Response for delete repost operation
type DeleteRepostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteRepostResponse) Reset() {
	*x = DeleteRepostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repost_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRepostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRepostResponse) ProtoMessage() {}

func (x *DeleteRepostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repost_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRepostResponse.ProtoReflect.Descriptor instead.
func (*DeleteRepostResponse) Descriptor() ([]byte, []int) {
	return file_repost_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRepostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Repost message definition
type Repost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalPostId string                 `protobuf:"bytes,3,opt,name=original_post_id,json=originalPostId,proto3" json:"original_post_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Repost) Reset() {
	*x = Repost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_repost_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Repost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repost) ProtoMessage() {}

func (x *Repost) ProtoReflect() protoreflect.Message {
	mi := &file_repost_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repost.ProtoReflect.Descriptor instead.
func (*Repost) Descriptor() ([]byte, []int) {
	return file_repost_proto_rawDescGZIP(), []int{7}
}

func (x *Repost) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Repost) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Repost) GetOriginalPostId() string {
	if x != nil {
		return x.OriginalPostId
	}
	return ""
}

func (x *Repost) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_repost_proto protoreflect.FileDescriptor

var file_repost_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x22, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x32, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x0e,
	0x52, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22,
	0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f,
	0x73, 0x74, 0x22, 0x37, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6f,
	0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x30, 0x0a, 0x14, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x96, 0x01,
	0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x28, 0x0a, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x6f,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x76, 0x65, 0x2d, 0x6d, 0x69, 0x72, 0x2f, 0x64,
	0x69, 0x69, 0x76, 0x69, 0x78, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_repost_proto_rawDescOnce sync.Once
	file_repost_proto_rawDescData = file_repost_proto_rawDesc
)

func file_repost_proto_rawDescGZIP() []byte {
	file_repost_proto_rawDescOnce.Do(func() {
		file_repost_proto_rawDescData = protoimpl.X.CompressGZIP(file_repost_proto_rawDescData)
	})
	return file_repost_proto_rawDescData
}

var file_repost_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_repost_proto_goTypes = []interface{}{
	(*CreateRepostRequest)(nil),     // 0: pb.CreateRepostRequest
	(*GetRepostRequest)(nil),        // 1: pb.GetRepostRequest
	(*GetRepostsByUserRequest)(nil), // 2: pb.GetRepostsByUserRequest
	(*DeleteRepostRequest)(nil),     // 3: pb.DeleteRepostRequest
	(*RepostResponse)(nil),          // 4: pb.RepostResponse
	(*RepostsResponse)(nil),         // 5: pb.RepostsResponse
	(*DeleteRepostResponse)(nil),    // 6: pb.DeleteRepostResponse
	(*Repost)(nil),                  // 7: pb.Repost
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_repost_proto_depIdxs = []int32{
	7, // 0: pb.RepostResponse.repost:type_name -> pb.Repost
	7, // 1: pb.RepostsResponse.reposts:type_name -> pb.Repost
	8, // 2: pb.Repost.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_repost_proto_init() }
func file_repost_proto_init() {
	if File_repost_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_repost_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRepostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repost_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRepostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repost_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRepostsByUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repost_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRepostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repost_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repost_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repost_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRepostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_repost_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Repost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_repost_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repost_proto_goTypes,
		DependencyIndexes: file_repost_proto_depIdxs,
		MessageInfos:      file_repost_proto_msgTypes,
	}.Build()
	File_repost_proto = out.File
	file_repost_proto_rawDesc = nil
	file_repost_proto_goTypes = nil
	file_repost_proto_depIdxs = nil
}
