// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: rpc_post_bkmk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's ID to get bookmarked posts.
type GetBookmarkedPostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNumber int32 `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize   int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *GetBookmarkedPostsRequest) Reset() {
	*x = GetBookmarkedPostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_post_bkmk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookmarkedPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookmarkedPostsRequest) ProtoMessage() {}

func (x *GetBookmarkedPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_post_bkmk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookmarkedPostsRequest.ProtoReflect.Descriptor instead.
func (*GetBookmarkedPostsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_post_bkmk_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookmarkedPostsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *GetBookmarkedPostsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// The message representing a single bookmarked post.
type BookmarkedPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post         *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	BookmarkedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=bookmarked_at,json=bookmarkedAt,proto3" json:"bookmarked_at,omitempty"`
}

func (x *BookmarkedPost) Reset() {
	*x = BookmarkedPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_post_bkmk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookmarkedPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookmarkedPost) ProtoMessage() {}

func (x *BookmarkedPost) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_post_bkmk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookmarkedPost.ProtoReflect.Descriptor instead.
func (*BookmarkedPost) Descriptor() ([]byte, []int) {
	return file_rpc_post_bkmk_proto_rawDescGZIP(), []int{1}
}

func (x *BookmarkedPost) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *BookmarkedPost) GetBookmarkedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BookmarkedAt
	}
	return nil
}

// The response message containing the list of bookmarked posts.
type GetBookmarkedPostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Posts   []*BookmarkedPost `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	HasMore bool              `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
}

func (x *GetBookmarkedPostsResponse) Reset() {
	*x = GetBookmarkedPostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_post_bkmk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookmarkedPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookmarkedPostsResponse) ProtoMessage() {}

func (x *GetBookmarkedPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_post_bkmk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookmarkedPostsResponse.ProtoReflect.Descriptor instead.
func (*GetBookmarkedPostsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_post_bkmk_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookmarkedPostsResponse) GetPosts() []*BookmarkedPost {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *GetBookmarkedPostsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// The request message containing the user's ID and the post's ID to delete a bookmark.
type DeleteBookmarkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBookmarkRequest) Reset() {
	*x = DeleteBookmarkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_post_bkmk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookmarkRequest) ProtoMessage() {}

func (x *DeleteBookmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_post_bkmk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookmarkRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookmarkRequest) Descriptor() ([]byte, []int) {
	return file_rpc_post_bkmk_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBookmarkRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// The response message containing the result of the delete bookmark action.
type DeleteBookmarkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteBookmarkResponse) Reset() {
	*x = DeleteBookmarkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_post_bkmk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookmarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookmarkResponse) ProtoMessage() {}

func (x *DeleteBookmarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_post_bkmk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookmarkResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookmarkResponse) Descriptor() ([]byte, []int) {
	return file_rpc_post_bkmk_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBookmarkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBookmarkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The response message containing the result of the bookmark action.
type BookmarkPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BookmarkPostResponse) Reset() {
	*x = BookmarkPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_post_bkmk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookmarkPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookmarkPostResponse) ProtoMessage() {}

func (x *BookmarkPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_post_bkmk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookmarkPostResponse.ProtoReflect.Descriptor instead.
func (*BookmarkPostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_post_bkmk_proto_rawDescGZIP(), []int{5}
}

func (x *BookmarkPostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BookmarkPostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The request message containing the user's ID and the post's ID to bookmark.
type BookmarkPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId string `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *BookmarkPostRequest) Reset() {
	*x = BookmarkPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_post_bkmk_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookmarkPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookmarkPostRequest) ProtoMessage() {}

func (x *BookmarkPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_post_bkmk_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookmarkPostRequest.ProtoReflect.Descriptor instead.
func (*BookmarkPostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_post_bkmk_proto_rawDescGZIP(), []int{6}
}

func (x *BookmarkPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

var File_rpc_post_bkmk_proto protoreflect.FileDescriptor

var file_rpc_post_bkmk_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x62, 0x6b, 0x6d, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x70, 0x6f, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0x6f, 0x0a, 0x0e, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x50,
	0x6f, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x73,
	0x74, 0x12, 0x3f, 0x0a, 0x0d, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x61, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x64, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61,
	0x73, 0x5f, 0x6d, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61,
	0x73, 0x4d, 0x6f, 0x72, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4c,
	0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4a, 0x0a, 0x14,
	0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x13, 0x42, 0x6f, 0x6f, 0x6b,
	0x6d, 0x61, 0x72, 0x6b, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x76, 0x65, 0x2d, 0x6d, 0x69, 0x72,
	0x2f, 0x64, 0x69, 0x69, 0x76, 0x69, 0x78, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_post_bkmk_proto_rawDescOnce sync.Once
	file_rpc_post_bkmk_proto_rawDescData = file_rpc_post_bkmk_proto_rawDesc
)

func file_rpc_post_bkmk_proto_rawDescGZIP() []byte {
	file_rpc_post_bkmk_proto_rawDescOnce.Do(func() {
		file_rpc_post_bkmk_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_post_bkmk_proto_rawDescData)
	})
	return file_rpc_post_bkmk_proto_rawDescData
}

var file_rpc_post_bkmk_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_post_bkmk_proto_goTypes = []interface{}{
	(*GetBookmarkedPostsRequest)(nil),  // 0: pb.GetBookmarkedPostsRequest
	(*BookmarkedPost)(nil),             // 1: pb.BookmarkedPost
	(*GetBookmarkedPostsResponse)(nil), // 2: pb.GetBookmarkedPostsResponse
	(*DeleteBookmarkRequest)(nil),      // 3: pb.DeleteBookmarkRequest
	(*DeleteBookmarkResponse)(nil),     // 4: pb.DeleteBookmarkResponse
	(*BookmarkPostResponse)(nil),       // 5: pb.BookmarkPostResponse
	(*BookmarkPostRequest)(nil),        // 6: pb.BookmarkPostRequest
	(*Post)(nil),                       // 7: pb.Post
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
}
var file_rpc_post_bkmk_proto_depIdxs = []int32{
	7, // 0: pb.BookmarkedPost.post:type_name -> pb.Post
	8, // 1: pb.BookmarkedPost.bookmarked_at:type_name -> google.protobuf.Timestamp
	1, // 2: pb.GetBookmarkedPostsResponse.posts:type_name -> pb.BookmarkedPost
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_post_bkmk_proto_init() }
func file_rpc_post_bkmk_proto_init() {
	if File_rpc_post_bkmk_proto != nil {
		return
	}
	file_post_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_post_bkmk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookmarkedPostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_post_bkmk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookmarkedPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_post_bkmk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookmarkedPostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_post_bkmk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBookmarkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_post_bkmk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBookmarkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_post_bkmk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookmarkPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_post_bkmk_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookmarkPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_post_bkmk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_post_bkmk_proto_goTypes,
		DependencyIndexes: file_rpc_post_bkmk_proto_depIdxs,
		MessageInfos:      file_rpc_post_bkmk_proto_msgTypes,
	}.Build()
	File_rpc_post_bkmk_proto = out.File
	file_rpc_post_bkmk_proto_rawDesc = nil
	file_rpc_post_bkmk_proto_goTypes = nil
	file_rpc_post_bkmk_proto_depIdxs = nil
}
