-- Enable PostGIS extension
CREATE EXTENSION IF NOT EXISTS postgis;


-- Add denomination_id and church_id columns if they don't exist in users
ALTER TABLE users
ADD COLUMN IF NOT EXISTS last_denomination_change timestamptz,
ADD COLUMN IF NOT EXISTS last_church_change timestamptz,
ADD COLUMN IF NOT EXISTS denomination_id INT,
ADD COLUMN IF NOT EXISTS church_id INT;


-- Create Denominations table if it does not exist
CREATE TABLE IF NOT EXISTS denominations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL
);

-- Create Churches table if it does not exist
CREATE TABLE IF NOT EXISTS churches (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id uuid NOT NULL,
  denomination_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  members_count int DEFAULT 0,
  FOREIGN KEY (auth_id) REFERENCES authentications(id),
  FOREIGN KEY (denomination_id) REFERENCES denominations(id)
);

CREATE TABLE IF NOT EXISTS church_locations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id uuid NOT NULL,
  address VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  postalCode VARCHAR(255) NOT NULL,
  lga VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  location GEOGRAPHY NOT NULL,
  FOREIGN KEY (auth_id) REFERENCES authentications(id)
);

-- Create User Denomination Membership table if it does not exist
CREATE TABLE IF NOT EXISTS user_denomination_membership (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  denomination_id INT NOT NULL,
  join_date timestamptz,
  leave_date timestamptz,
  active BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (user_id) REFERENCES authentications(id),
  FOREIGN KEY (denomination_id) REFERENCES denominations(id)
);

-- Create User Church Membership table if it does not exist
CREATE TABLE IF NOT EXISTS user_church_membership (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  church_id INT NOT NULL,
  join_date timestamptz,
  leave_date timestamptz,
  active BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (user_id) REFERENCES authentications(id),
  FOREIGN KEY (church_id) REFERENCES churches(id)
);

-- Now, add the foreign keys in users
ALTER TABLE users
ADD FOREIGN KEY (denomination_id) REFERENCES denominations(id),
ADD FOREIGN KEY (church_id) REFERENCES churches(id);

-- Add necessary indexes for users
CREATE INDEX IF NOT EXISTS idx_user_denomination_membership_user_id ON user_denomination_membership (user_id);
CREATE INDEX IF NOT EXISTS idx_user_church_membership_user_id ON user_church_membership (user_id);

-- TODO: Add index to church on church_id, c.id
CREATE INDEX IF NOT EXISTS idx_user_church_membership_user_id ON user_church_membership (user_id);

CREATE INDEX ON "user_church_membership" (
        "active"
    );
CREATE UNIQUE INDEX idx_user_active_membership ON user_denomination_membership(user_id) WHERE active;
CREATE UNIQUE INDEX idx_user_church_active_membership ON user_church_membership(user_id) WHERE active;