CREATE TABLE "hashtag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hash_tag" VARCHAR UNIQUE
);

CREATE TABLE "post_hashtag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" uuid not null,
  "hashtag_id" int
);

CREATE TABLE "bookmarks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid not null,
  "post_id" uuid not null,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "blocked_users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "blocking_user_id" uuid not null,
  "blocked_user_id" uuid not null,
  "reason" varchar,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "reported_posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" uuid not null,
  "user_id" uuid not null,
  "reason" varchar,
  "created_at" timestamptz DEFAULT (now())
);

-- TODO: Admin
CREATE TABLE "moderation_queue" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid not null,
  "post_id" uuid not null,
  "report_reason" varchar,
  "status" varchar,
  "created_at" timestamptz DEFAULT (now())
);

CREATE INDEX ON "hashtag" ("hash_tag", "id");

CREATE INDEX ON "post_hashtag" ("hashtag_id", "id", "post_id");

CREATE INDEX ON "bookmarks" ("user_id", "post_id");

CREATE INDEX ON "blocked_users" ("blocked_user_id", "blocking_user_id");

CREATE INDEX ON "reported_posts" ("post_id", "user_id");

CREATE INDEX ON "moderation_queue" ("user_id", "post_id");

ALTER TABLE "post_hashtag" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "post_hashtag" ADD FOREIGN KEY ("hashtag_id") REFERENCES "hashtag" ("id");

ALTER TABLE "bookmarks" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");

ALTER TABLE "bookmarks" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "bookmarks" ADD CONSTRAINT unique_user_post UNIQUE ("user_id", "post_id");

ALTER TABLE "blocked_users" ADD CONSTRAINT unique_blocked_user UNIQUE ("blocking_user_id", "blocked_user_id");

ALTER TABLE "blocked_users" ADD FOREIGN KEY ("blocking_user_id") REFERENCES "authentications" ("id");

ALTER TABLE "blocked_users" ADD FOREIGN KEY ("blocked_user_id") REFERENCES "authentications" ("id");

ALTER TABLE "reported_posts" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "reported_posts" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");

ALTER TABLE "moderation_queue" ADD FOREIGN KEY ("user_id") REFERENCES "authentications" ("id");

ALTER TABLE "moderation_queue" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");