// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ParticipantStatus string

const (
	ParticipantStatusInvited  ParticipantStatus = "invited"
	ParticipantStatusAccepted ParticipantStatus = "accepted"
	ParticipantStatusDeclined ParticipantStatus = "declined"
)

func (e *ParticipantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipantStatus(s)
	case string:
		*e = ParticipantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipantStatus: %T", src)
	}
	return nil
}

type NullParticipantStatus struct {
	ParticipantStatus ParticipantStatus `json:"participant_status"`
	Valid             bool              `json:"valid"` // Valid is true if ParticipantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipantStatus), nil
}

type Account struct {
	ID            int32          `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	AccountName   sql.NullString `json:"account_name"`
	AccountNumber sql.NullString `json:"account_number"`
	BankName      sql.NullString `json:"bank_name"`
	TotalCoin     sql.NullString `json:"total_coin"`
}

type AccountRecoveryRequest struct {
	ID            int32        `json:"id"`
	UserID        uuid.UUID    `json:"user_id"`
	Email         string       `json:"email"`
	Used          sql.NullBool `json:"used"`
	RecoveryToken string       `json:"recovery_token"`
	RequestedAt   sql.NullTime `json:"requested_at"`
	ExpiresAt     time.Time    `json:"expires_at"`
	CompletedAt   sql.NullTime `json:"completed_at"`
}

type Announcement struct {
	ID          uuid.UUID     `json:"id"`
	UserID      uuid.UUID     `json:"user_id"`
	Title       string        `json:"title"`
	Content     string        `json:"content"`
	TotalImages sql.NullInt32 `json:"total_images"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	SuspendedAt sql.NullTime  `json:"suspended_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
}

type AnnouncementNotification struct {
	ID             int32     `json:"id"`
	NotificationID int32     `json:"notification_id"`
	NewsID         uuid.UUID `json:"news_id"`
	AuthorID       uuid.UUID `json:"author_id"`
	UserID         uuid.UUID `json:"user_id"`
}

type Authentication struct {
	ID                  uuid.UUID      `json:"id"`
	Email               string         `json:"email"`
	Phone               sql.NullString `json:"phone"`
	Username            sql.NullString `json:"username"`
	PasswordHash        string         `json:"password_hash"`
	UserType            string         `json:"user_type"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	IsSuspended         sql.NullBool   `json:"is_suspended"`
	IsDeleted           sql.NullBool   `json:"is_deleted"`
	IsVerified          sql.NullBool   `json:"is_verified"`
	IsEmailVerified     sql.NullBool   `json:"is_email_verified"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	VerifiedAt          sql.NullTime   `json:"verified_at"`
	SuspendedAt         sql.NullTime   `json:"suspended_at"`
	LoginAttempts       sql.NullInt32  `json:"login_attempts"`
	PasswordLastChanged sql.NullTime   `json:"password_last_changed"`
	LockoutDuration     sql.NullInt32  `json:"lockout_duration"`
	LockoutUntil        sql.NullTime   `json:"lockout_until"`
	IsMfaEnabled        sql.NullBool   `json:"is_mfa_enabled"`
}

type BlockedUser struct {
	ID             int32          `json:"id"`
	BlockingUserID uuid.UUID      `json:"blocking_user_id"`
	BlockedUserID  uuid.UUID      `json:"blocked_user_id"`
	Reason         sql.NullString `json:"reason"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Bookmark struct {
	ID        int32        `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	PostID    uuid.UUID    `json:"post_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type ChangeIdentifierRequest struct {
	ID         int32        `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	Identifier string       `json:"identifier"`
	Token      string       `json:"token"`
	Type       string       `json:"type"`
	Used       sql.NullBool `json:"used"`
	CreatedAt  sql.NullTime `json:"created_at"`
	ExpiresAt  time.Time    `json:"expires_at"`
}

type Church struct {
	ID             int32         `json:"id"`
	AuthID         uuid.UUID     `json:"auth_id"`
	DenominationID int32         `json:"denomination_id"`
	Name           string        `json:"name"`
	MembersCount   sql.NullInt32 `json:"members_count"`
}

type ChurchLocation struct {
	ID         int32       `json:"id"`
	AuthID     uuid.UUID   `json:"auth_id"`
	Address    string      `json:"address"`
	City       string      `json:"city"`
	Postalcode string      `json:"postalcode"`
	Lga        string      `json:"lga"`
	State      string      `json:"state"`
	Country    string      `json:"country"`
	Location   interface{} `json:"location"`
}

type ChurchProgram struct {
	ID               int32          `json:"id"`
	ChurchID         int32          `json:"church_id"`
	ProgramType      string         `json:"program_type"`
	ProgramName      string         `json:"program_name"`
	ProgramDesc      sql.NullString `json:"program_desc"`
	ProgramDay       sql.NullString `json:"program_day"`
	ProgramStartTime sql.NullTime   `json:"program_start_time"`
	ProgramEndTime   sql.NullTime   `json:"program_end_time"`
	ProgramFreq      sql.NullString `json:"program_freq"`
	ProgramImageUrl  sql.NullString `json:"program_image_url"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type ChurchProject struct {
	ID                 int32          `json:"id"`
	ChurchID           int32          `json:"church_id"`
	ProjectName        string         `json:"project_name"`
	ProjectDescription sql.NullString `json:"project_description"`
	TargetAmount       string         `json:"target_amount"`
	DonatedAmount      string         `json:"donated_amount"`
	StartDate          sql.NullTime   `json:"start_date"`
	EndDate            sql.NullTime   `json:"end_date"`
	Visibility         sql.NullBool   `json:"visibility"`
	Completed          sql.NullBool   `json:"completed"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type Denomination struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type EmailVerificationRequest struct {
	ID         int64        `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	Email      string       `json:"email"`
	Token      string       `json:"token"`
	IsVerified sql.NullBool `json:"is_verified"`
	CreatedAt  sql.NullTime `json:"created_at"`
	ExpiresAt  time.Time    `json:"expires_at"`
}

type EntityProfile struct {
	ID             int32          `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	ImageUrl       sql.NullString `json:"image_url"`
	FollowingCount sql.NullInt32  `json:"following_count"`
	FollowersCount sql.NullInt32  `json:"followers_count"`
	EntityType     string         `json:"entity_type"`
	PostsCount     sql.NullInt32  `json:"posts_count"`
	HeaderImageUrl sql.NullString `json:"header_image_url"`
	About          sql.NullString `json:"about"`
	Website        sql.NullString `json:"website"`
}

type Follow struct {
	FollowerUserID  uuid.UUID    `json:"follower_user_id"`
	FollowingUserID uuid.UUID    `json:"following_user_id"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type FollowNotification struct {
	NotificationID  int32     `json:"notification_id"`
	AuthorID        uuid.UUID `json:"author_id"`
	FollowingUserID uuid.UUID `json:"following_user_id"`
}

type Group struct {
	ID             int32          `json:"id"`
	DenominationID int32          `json:"denomination_id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
}

type GroupForum struct {
	ID        int32        `json:"id"`
	GroupID   int32        `json:"group_id"`
	UserID    uuid.UUID    `json:"user_id"`
	Message   string       `json:"message"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Hashtag struct {
	ID      int32          `json:"id"`
	HashTag sql.NullString `json:"hash_tag"`
}

type Like struct {
	ID     int32     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

type MentionsNotification struct {
	ID               int32     `json:"id"`
	NotificationID   int32     `json:"notification_id"`
	PostID           uuid.UUID `json:"post_id"`
	AuthorID         uuid.UUID `json:"author_id"`
	MentioningUserID uuid.UUID `json:"mentioning_user_id"`
}

type ModerationQueue struct {
	ID           int32          `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	PostID       uuid.UUID      `json:"post_id"`
	ReportReason sql.NullString `json:"report_reason"`
	Status       sql.NullString `json:"status"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Notification struct {
	ID     int32        `json:"id"`
	UserID uuid.UUID    `json:"user_id"`
	Type   string       `json:"type"`
	Read   bool         `json:"read"`
	Time   sql.NullTime `json:"time"`
}

type Organization struct {
	ID          int32          `json:"id"`
	ChurchID    int32          `json:"church_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type OrganizationForum struct {
	ID             int32        `json:"id"`
	OrganizationID int32        `json:"organization_id"`
	UserID         uuid.UUID    `json:"user_id"`
	Message        string       `json:"message"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type PasswordResetRequest struct {
	ID        int32        `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Email     string       `json:"email"`
	Token     string       `json:"token"`
	Used      sql.NullBool `json:"used"`
	CreatedAt sql.NullTime `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
}

type Post struct {
	ID          uuid.UUID     `json:"id"`
	UserID      uuid.UUID     `json:"user_id"`
	Content     string        `json:"content"`
	TotalImages sql.NullInt32 `json:"total_images"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	SuspendedAt sql.NullTime  `json:"suspended_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
}

type PostComment struct {
	ID          int32        `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	PostID      uuid.UUID    `json:"post_id"`
	CommentText string       `json:"comment_text"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type PostCommentNotification struct {
	ID             int32     `json:"id"`
	NotificationID int32     `json:"notification_id"`
	PostID         uuid.UUID `json:"post_id"`
	AuthorID       uuid.UUID `json:"author_id"`
	CommentUserID  uuid.UUID `json:"comment_user_id"`
}

type PostHashtag struct {
	ID        int32         `json:"id"`
	PostID    uuid.UUID     `json:"post_id"`
	HashtagID sql.NullInt32 `json:"hashtag_id"`
}

type PostLikeNotification struct {
	ID             int32     `json:"id"`
	NotificationID int32     `json:"notification_id"`
	PostID         uuid.UUID `json:"post_id"`
	AuthorID       uuid.UUID `json:"author_id"`
	LikeUserID     uuid.UUID `json:"like_user_id"`
}

type PostMention struct {
	ID              int32     `json:"id"`
	PostID          uuid.UUID `json:"post_id"`
	MentionedUserID uuid.UUID `json:"mentioned_user_id"`
}

type PostView struct {
	ID     int32     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

type PostsImage struct {
	ID       int32          `json:"id"`
	PostID   uuid.UUID      `json:"post_id"`
	ImageUrl sql.NullString `json:"image_url"`
	Caption  sql.NullString `json:"caption"`
}

type PostsMetric struct {
	ID       int32         `json:"id"`
	PostID   uuid.UUID     `json:"post_id"`
	Views    sql.NullInt32 `json:"views"`
	Likes    sql.NullInt32 `json:"likes"`
	Comments sql.NullInt32 `json:"comments"`
	Reposts  sql.NullInt32 `json:"reposts"`
}

type PrayerInviteNotification struct {
	NotificationID int32     `json:"notification_id"`
	AuthorID       uuid.UUID `json:"author_id"`
	InvitingUserID uuid.UUID `json:"inviting_user_id"`
	RoomID         string    `json:"room_id"`
}

type PrayerParticipant struct {
	ParticipantID int32                 `json:"participant_id"`
	RoomID        string                `json:"room_id"`
	UserID        uuid.UUID             `json:"user_id"`
	Status        NullParticipantStatus `json:"status"`
}

type PrayerRoom struct {
	RoomID    string         `json:"room_id"`
	AuthorID  uuid.UUID      `json:"author_id"`
	Name      sql.NullString `json:"name"`
	CreatedAt sql.NullTime   `json:"created_at"`
	StartTime sql.NullTime   `json:"start_time"`
	EndTime   sql.NullTime   `json:"end_time"`
}

type ProjectDonation struct {
	ID             int32        `json:"id"`
	ProjectID      int32        `json:"project_id"`
	UserID         uuid.UUID    `json:"user_id"`
	DonationAmount string       `json:"donation_amount"`
	DonatedAt      sql.NullTime `json:"donated_at"`
}

type ReportedPost struct {
	ID        int32          `json:"id"`
	PostID    uuid.UUID      `json:"post_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Reason    sql.NullString `json:"reason"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Repost struct {
	ID             int32        `json:"id"`
	UserID         uuid.UUID    `json:"user_id"`
	OriginalPostID uuid.UUID    `json:"original_post_id"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Session struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	RefreshToken    string         `json:"refresh_token"`
	RefreshTokenExp time.Time      `json:"refresh_token_exp"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	InvalidatedAt   sql.NullTime   `json:"invalidated_at"`
	LastActiveAt    sql.NullTime   `json:"last_active_at"`
	BlockedAt       sql.NullTime   `json:"blocked_at"`
	UserAgent       string         `json:"user_agent"`
	IpAddress       pqtype.Inet    `json:"ip_address"`
	FcmToken        sql.NullString `json:"fcm_token"`
}

type TwoFactorBackupCode struct {
	ID     int32        `json:"id"`
	UserID uuid.UUID    `json:"user_id"`
	Code   string       `json:"code"`
	Used   sql.NullBool `json:"used"`
}

type TwoFactorRevocation struct {
	ID               int32          `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
	RevocationReason sql.NullString `json:"revocation_reason"`
}

type TwoFactorSecret struct {
	ID        int32        `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	SecretKey string       `json:"secret_key"`
	IsActive  sql.NullBool `json:"is_active"`
}

type User struct {
	ID                     int32          `json:"id"`
	UserID                 uuid.UUID      `json:"user_id"`
	FirstName              sql.NullString `json:"first_name"`
	LastName               sql.NullString `json:"last_name"`
	LastDenominationChange sql.NullTime   `json:"last_denomination_change"`
	LastChurchChange       sql.NullTime   `json:"last_church_change"`
	DenominationID         sql.NullInt32  `json:"denomination_id"`
	ChurchID               sql.NullInt32  `json:"church_id"`
}

type UserChurchMembership struct {
	ID        int32        `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	ChurchID  int32        `json:"church_id"`
	JoinDate  sql.NullTime `json:"join_date"`
	LeaveDate sql.NullTime `json:"leave_date"`
	Active    sql.NullBool `json:"active"`
}

type UserDenominationMembership struct {
	ID             int32        `json:"id"`
	UserID         uuid.UUID    `json:"user_id"`
	DenominationID int32        `json:"denomination_id"`
	JoinDate       sql.NullTime `json:"join_date"`
	LeaveDate      sql.NullTime `json:"leave_date"`
	Active         sql.NullBool `json:"active"`
}

type UserGroupMembership struct {
	ID       int32        `json:"id"`
	GroupID  int32        `json:"group_id"`
	UserID   uuid.UUID    `json:"user_id"`
	JoinDate sql.NullTime `json:"join_date"`
	IsAdmin  sql.NullBool `json:"is_admin"`
}

type UserLogin struct {
	ID        int32          `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	LoginAt   sql.NullTime   `json:"login_at"`
	IpAddress pqtype.Inet    `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
}

type UserOrganizationMembership struct {
	ID             int32         `json:"id"`
	OrganizationID sql.NullInt32 `json:"organization_id"`
	UserID         uuid.UUID     `json:"user_id"`
	JoinDate       sql.NullTime  `json:"join_date"`
	Approved       sql.NullBool  `json:"approved"`
	IsAdmin        sql.NullBool  `json:"is_admin"`
}

type UserRole struct {
	ID     int32     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	RoleID int32     `json:"role_id"`
}
