// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: sm_recommend_gpt4.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getPostsRecommendationDisFunc = `-- name: GetPostsRecommendationDisFunc :many
WITH UserActivityRecommendations AS (
    SELECT p.id, p.user_id, p.content, p.total_images, p.created_at, p.updated_at, p.suspended_at, p.deleted_at, ARRAY_AGG(pi.image_url) AS image_urls
    FROM posts p
    LEFT JOIN posts_images pi ON p.id = pi.post_id
    WHERE p.user_id = $1 OR p.id IN (SELECT post_id FROM likes WHERE user_id = $1)
    GROUP BY p.id
    ORDER BY p.created_at DESC
    LIMIT 3
),

PopularPostsRecommendations AS (
    SELECT p.id, p.user_id, p.content, p.total_images, p.created_at, p.updated_at, p.suspended_at, p.deleted_at, ARRAY_AGG(pi.image_url) AS image_urls
    FROM posts p
    LEFT JOIN posts_images pi ON p.id = pi.post_id
    JOIN posts_metrics pm ON p.id = pm.post_id
    GROUP BY p.id, pm.likes
    ORDER BY pm.likes DESC
    LIMIT 3
),

FollowedUsersRecommendations AS (
    SELECT p.id, p.user_id, p.content, p.total_images, p.created_at, p.updated_at, p.suspended_at, p.deleted_at, ARRAY_AGG(pi.image_url) AS image_urls
    FROM posts p
    LEFT JOIN posts_images pi ON p.id = pi.post_id
    JOIN follow f ON p.user_id = f.following_user_id
    WHERE f.follower_user_id = $1
    GROUP BY p.id
    ORDER BY p.created_at DESC
    LIMIT 2
),

CollaborativeFilteringRecommendations AS (
    SELECT p.id, p.user_id, p.content, p.total_images, p.created_at, p.updated_at, p.suspended_at, p.deleted_at, ARRAY_AGG(pi.image_url) AS image_urls
    FROM posts p
    LEFT JOIN posts_images pi ON p.id = pi.post_id
    JOIN likes l ON p.id = l.post_id
    WHERE l.user_id IN (
        SELECT following_user_id
        FROM follow
        WHERE follower_user_id = $1
    )
    AND p.id NOT IN (
        -- Exclude the user's own posts
        SELECT id
        FROM posts
        WHERE user_id = $1
    )
    GROUP BY p.id
    ORDER BY p.created_at DESC
    LIMIT 2
),

CombinedRecommendations AS (
    SELECT id, user_id, content, total_images, created_at, updated_at, suspended_at, deleted_at, image_urls FROM UserActivityRecommendations
    UNION
    SELECT id, user_id, content, total_images, created_at, updated_at, suspended_at, deleted_at, image_urls FROM PopularPostsRecommendations
    UNION
    SELECT id, user_id, content, total_images, created_at, updated_at, suspended_at, deleted_at, image_urls FROM FollowedUsersRecommendations
    UNION
    SELECT id, user_id, content, total_images, created_at, updated_at, suspended_at, deleted_at, image_urls FROM CollaborativeFilteringRecommendations
)
SELECT id, user_id, content, total_images, created_at, updated_at, suspended_at, deleted_at, image_urls FROM CombinedRecommendations
ORDER BY created_at DESC
LIMIT 10
`

type GetPostsRecommendationDisFuncRow struct {
	ID          uuid.UUID     `json:"id"`
	UserID      uuid.UUID     `json:"user_id"`
	Content     string        `json:"content"`
	TotalImages sql.NullInt32 `json:"total_images"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	SuspendedAt sql.NullTime  `json:"suspended_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
	ImageUrls   interface{}   `json:"image_urls"`
}

// Recommendations based on popularity
// Recommendations from followed users
// Collaborative Filtering Recommendations
// Combine all recommendations
func (q *Queries) GetPostsRecommendationDisFunc(ctx context.Context, userID uuid.UUID) ([]GetPostsRecommendationDisFuncRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsRecommendationDisFunc, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostsRecommendationDisFuncRow{}
	for rows.Next() {
		var i GetPostsRecommendationDisFuncRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.TotalImages,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuspendedAt,
			&i.DeletedAt,
			&i.ImageUrls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsRecommendationNewWrong = `-- name: GetPostsRecommendationNewWrong :many
WITH UserActivityRecommendations AS (
    SELECT p.id, p.user_id, p.content, p.total_images, p.created_at, p.updated_at, p.suspended_at, p.deleted_at, COALESCE(ARRAY_AGG(pi.image_url) FILTER (WHERE pi.image_url IS NOT NULL), '{}') AS image_urls
    FROM posts p
    LEFT JOIN posts_images pi ON p.id = pi.post_id
    WHERE p.user_id = $1 OR p.id IN (SELECT post_id FROM likes WHERE user_id = $1)
    GROUP BY p.id
    ORDER BY p.created_at DESC
    LIMIT 3
),

PopularPostsRecommendations AS (
    SELECT p.id, p.user_id, p.content, p.total_images, p.created_at, p.updated_at, p.suspended_at, p.deleted_at, COALESCE(ARRAY_AGG(pi.image_url) FILTER (WHERE pi.image_url IS NOT NULL), '{}') AS image_urls
    FROM posts p
    LEFT JOIN posts_images pi ON p.id = pi.post_id
    JOIN posts_metrics pm ON p.id = pm.post_id
    GROUP BY p.id, pm.likes
    ORDER BY pm.likes DESC
    LIMIT 3
),

FollowedUsersRecommendations AS (
    SELECT p.id, p.user_id, p.content, p.total_images, p.created_at, p.updated_at, p.suspended_at, p.deleted_at, COALESCE(ARRAY_AGG(pi.image_url) FILTER (WHERE pi.image_url IS NOT NULL), '{}') AS image_urls
    FROM posts p
    LEFT JOIN posts_images pi ON p.id = pi.post_id
    JOIN follow f ON p.user_id = f.following_user_id
    WHERE f.follower_user_id = $1
    GROUP BY p.id
    ORDER BY p.created_at DESC
    LIMIT 2
),

CollaborativeFilteringRecommendations AS (
    SELECT p.id, p.user_id, p.content, p.total_images, p.created_at, p.updated_at, p.suspended_at, p.deleted_at, COALESCE(ARRAY_AGG(pi.image_url) FILTER (WHERE pi.image_url IS NOT NULL), '{}') AS image_urls
    FROM posts p
    LEFT JOIN posts_images pi ON p.id = pi.post_id
    JOIN likes l ON p.id = l.post_id
    WHERE l.user_id IN (
        SELECT following_user_id
        FROM follow
        WHERE follower_user_id = $1
    )
    AND p.id NOT IN (
        -- Exclude the user's own posts
        SELECT id
        FROM posts
        WHERE user_id = $1
    )
    GROUP BY p.id
    ORDER BY p.created_at DESC
    LIMIT 2
),

CombinedRecommendations AS (
    SELECT id, user_id, content, total_images, created_at, updated_at, suspended_at, deleted_at, image_urls FROM UserActivityRecommendations
    UNION
    SELECT id, user_id, content, total_images, created_at, updated_at, suspended_at, deleted_at, image_urls FROM PopularPostsRecommendations
    UNION
    SELECT id, user_id, content, total_images, created_at, updated_at, suspended_at, deleted_at, image_urls FROM FollowedUsersRecommendations
    UNION
    SELECT id, user_id, content, total_images, created_at, updated_at, suspended_at, deleted_at, image_urls FROM CollaborativeFilteringRecommendations
)
SELECT id, user_id, content, total_images, created_at, updated_at, suspended_at, deleted_at, image_urls FROM CombinedRecommendations
ORDER BY created_at DESC
LIMIT 10
`

type GetPostsRecommendationNewWrongRow struct {
	ID          uuid.UUID     `json:"id"`
	UserID      uuid.UUID     `json:"user_id"`
	Content     string        `json:"content"`
	TotalImages sql.NullInt32 `json:"total_images"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	SuspendedAt sql.NullTime  `json:"suspended_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
	ImageUrls   interface{}   `json:"image_urls"`
}

// Recommendations based on popularity
// Recommendations from followed users
// Collaborative Filtering Recommendations
// Combine all recommendations
func (q *Queries) GetPostsRecommendationNewWrong(ctx context.Context, userID uuid.UUID) ([]GetPostsRecommendationNewWrongRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsRecommendationNewWrong, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostsRecommendationNewWrongRow{}
	for rows.Next() {
		var i GetPostsRecommendationNewWrongRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.TotalImages,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuspendedAt,
			&i.DeletedAt,
			&i.ImageUrls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
