// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: views.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const incrementViewCount = `-- name: IncrementViewCount :exec
UPDATE posts_metrics
SET views = views + 1
WHERE post_id = $1
`

func (q *Queries) IncrementViewCount(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementViewCount, postID)
	return err
}
