// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: rpc_church_acct.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateAccountDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountName   string `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	BankName      string `protobuf:"bytes,3,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
}

func (x *UpdateAccountDetailsRequest) Reset() {
	*x = UpdateAccountDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_church_acct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAccountDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountDetailsRequest) ProtoMessage() {}

func (x *UpdateAccountDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_church_acct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountDetailsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_church_acct_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateAccountDetailsRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *UpdateAccountDetailsRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *UpdateAccountDetailsRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

type UpdateAccountDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateAccountDetailsResponse) Reset() {
	*x = UpdateAccountDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_church_acct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAccountDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountDetailsResponse) ProtoMessage() {}

func (x *UpdateAccountDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_church_acct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountDetailsResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountDetailsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_church_acct_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateAccountDetailsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_rpc_church_acct_proto protoreflect.FileDescriptor

var file_rpc_church_acct_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x68, 0x75, 0x72, 0x63, 0x68, 0x5f, 0x61, 0x63, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x84, 0x01, 0x0a, 0x1b,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x30, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x76, 0x65, 0x2d, 0x6d, 0x69, 0x72, 0x2f, 0x64, 0x69, 0x69,
	0x76, 0x69, 0x78, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_church_acct_proto_rawDescOnce sync.Once
	file_rpc_church_acct_proto_rawDescData = file_rpc_church_acct_proto_rawDesc
)

func file_rpc_church_acct_proto_rawDescGZIP() []byte {
	file_rpc_church_acct_proto_rawDescOnce.Do(func() {
		file_rpc_church_acct_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_church_acct_proto_rawDescData)
	})
	return file_rpc_church_acct_proto_rawDescData
}

var file_rpc_church_acct_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_church_acct_proto_goTypes = []interface{}{
	(*UpdateAccountDetailsRequest)(nil),  // 0: pb.UpdateAccountDetailsRequest
	(*UpdateAccountDetailsResponse)(nil), // 1: pb.UpdateAccountDetailsResponse
}
var file_rpc_church_acct_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_church_acct_proto_init() }
func file_rpc_church_acct_proto_init() {
	if File_rpc_church_acct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_church_acct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAccountDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_church_acct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAccountDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_church_acct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_church_acct_proto_goTypes,
		DependencyIndexes: file_rpc_church_acct_proto_depIdxs,
		MessageInfos:      file_rpc_church_acct_proto_msgTypes,
	}.Build()
	File_rpc_church_acct_proto = out.File
	file_rpc_church_acct_proto_rawDesc = nil
	file_rpc_church_acct_proto_goTypes = nil
	file_rpc_church_acct_proto_depIdxs = nil
}
